name: Deploy Serverless Python Lambda (prod)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Serverless to Prod
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.x # used for installing the serverless-python-requirements dependency from NPM
    steps:
      # --------- use Python to install Python dependencies and run linter, tests, etc. ---------
      - uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install Node dependencies
        run: npm ci

      - name: Serverless Deploy
        uses: serverless/github-action@v3
        with:
          args: deploy --function hello-world-application-prod --stage prod
        env:
          # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS credentials directly
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}